### PR TITLE
Challenge

### PR DESCRIPTION
**Pull request by stojce**

### CODE REVIEW

**Comment by alexandr2110pro** [comment]
@stojce How are you? Can I review already?

**Comment by stojce** [comment]
@alexandr2110pro is everything ok with this PR?

**Review by alexandr2110pro — APPROVED** [review]
@stojce 
I've asked just to make sure, you've done everything you've planned and it supposed to be reviewed already.

To me your code is good in general, the implementation looks like what I've expected to see in terms of structure and architecture as well.

Probably in production, I would add some comments but as for the test challenge its very good.

**Comment by alexandr2110pro** [comment]
I have some questions, though.

What is your thinking about named and default exports? What is preferred in which cases, what are pros/cons from your experience & etc?

**Comment by stojce** [comment]
I usually don't use default exports: 
 - import syntax is same for one or more imports,
 - if we need to add more exports to same file or remove default export, it won't brake any import in other files.

This is just for convenience only.

**Comment by alexandr2110pro** [comment]
Makes sense @stojce  Personally I also prefer named exports in 90%. 

But there is a widely used practice to use default export if you export only 1 unit(class/obj/...) from the module. Usually, people say that it is easier to use such modules in the client code, since you don't need to change the name if the source changes. What do you think about that?

**Comment by stojce** [comment]
I still think that named is more consistent. Anyway, if there are adopted coding standard, and default exports are defined, I don't mind using them.

**Pull request merged**
